create extension if not exists pgcrypto;

create table if not exists public.slates (
  id uuid primary key default gen_random_uuid(),
  slate_date date not null unique,
  generated_at timestamptz not null,
  source_status jsonb not null default '{}'::jsonb,
  warnings jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.predictions (
  id bigint generated by default as identity primary key,
  slate_id uuid not null references public.slates(id) on delete cascade,
  slate_date date not null,
  game_pk bigint not null,
  player_id bigint not null,
  player_name text not null,
  team text not null,
  opponent text not null,
  lineup_slot smallint,
  hit_index smallint not null check (hit_index between 0 and 100),
  probability numeric(8,6) not null check (probability between 0 and 1),
  fair_american_odds integer not null,
  confidence text not null,
  factors jsonb not null default '{}'::jsonb,
  explanation jsonb not null default '[]'::jsonb,
  market_bookmaker text,
  market_line numeric(6,2),
  market_over_price integer,
  market_no_vig_probability numeric(8,6),
  market_edge numeric(8,6),
  actual_hits smallint,
  result text check (result in ('hit', 'miss')),
  settled_at timestamptz,
  created_at timestamptz not null default now(),
  unique (slate_date, game_pk, player_id)
);

create table if not exists public.parlays (
  id bigint generated by default as identity primary key,
  slate_id uuid not null references public.slates(id) on delete cascade,
  slate_date date not null,
  rank smallint not null,
  parlay_key text not null,
  legs jsonb not null,
  probability numeric(8,6) not null check (probability between 0 and 1),
  fair_american_odds integer not null,
  parlay_index smallint not null check (parlay_index between 0 and 100),
  same_game boolean not null default false,
  estimated_market_odds integer,
  market_implied_probability numeric(8,6),
  model_edge numeric(8,6),
  market_odds integer,
  stake numeric(12,2),
  payout numeric(12,2),
  result text check (result in ('win', 'loss', 'push')),
  settled_at timestamptz,
  created_at timestamptz not null default now(),
  unique (slate_date, parlay_key)
);

create index if not exists predictions_date_index on public.predictions (slate_date desc);
create index if not exists predictions_player_index on public.predictions (player_id, slate_date desc);
create index if not exists parlays_date_index on public.parlays (slate_date desc);

alter table public.slates enable row level security;
alter table public.predictions enable row level security;
alter table public.parlays enable row level security;

-- The app writes through the server-only service role. Add authenticated read policies
-- later if you introduce user accounts. Never expose SUPABASE_SERVICE_ROLE_KEY in the browser.

create table if not exists public.slate_cache (
  slate_date date primary key,
  payload jsonb,
  building boolean not null default false,
  error text,
  updated_at timestamptz not null default now()
);

alter table public.slate_cache enable row level security;
